# Generated by Django 4.1.6 on 2023-02-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_manager', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
