# Generated by Django 4.1.6 on 2023-02-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_manager', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
